db:
  build: db/
  environment:
    POSTGRES_USER: odoo
    POSTGRES_PASSWORD: odoo
  stdin_open: true
  tty: true
  
odoo:
  build: odoo/
  ports:
    - "127.0.0.1:80:21000" 
  stdin_open: true
  tty: true
